const Discord = require('discord.js')

exports.run = (client, message, args, guild) => {

    let role10 = message.guild.roles.find("name", "Commander 10");
    let role20 = message.guild.roles.find("name", "Commander 20");
    let role30 = message.guild.roles.find("name", "Commander 30");
    let role40 = message.guild.roles.find("name", "Commander 40");
    let role50 = message.guild.roles.find("name", "Commander 50");
    let role60 = message.guild.roles.find("name", "Commander 60");
    let role70 = message.guild.roles.find("name", "Commander 70");
    let role80 = message.guild.roles.find("name", "Commander 80");
    let role90 = message.guild.roles.find("name", "Commander 90");
    let role100 = message.guild.roles.find("name", "Commander 100");
    let role110 = message.guild.roles.find("name", "Commander 110");
    let role120 = message.guild.roles.find("name", "Commander 120");
    let role130 = message.guild.roles.find("name", "Commander 130");
    let role140 = message.guild.roles.find("name", "Commander 140");
    let role150 = message.guild.roles.find("name", "Commander 150");
    let role160 = message.guild.roles.find("name", "Commander 160");
    let role170 = message.guild.roles.find("name", "Commander 170");
    let role180 = message.guild.roles.find("name", "Commander 180");
    let role190 = message.guild.roles.find("name", "Commander 190");
    let role200 = message.guild.roles.find("name", "Commander 200");
    let role210 = message.guild.roles.find("name", "Commander 210");
    let role220 = message.guild.roles.find("name", "Commander 220");
    let role230 = message.guild.roles.find("name", "Commander 230");
    let role240 = message.guild.roles.find("name", "Commander 240");
    let role250 = message.guild.roles.find("name", "Commander 250");
    let role260 = message.guild.roles.find("name", "Commander 260");
    let role270 = message.guild.roles.find("name", "Commander 270");
    let role280 = message.guild.roles.find("name", "Commander 280");
    let role290 = message.guild.roles.find("name", "Commander 290");
    let role300 = message.guild.roles.find("name", "Commander 300");
    let role310 = message.guild.roles.find("name", "Commander 310");
    let role320 = message.guild.roles.find("name", "Commander 320");
    let role330 = message.guild.roles.find("name", "Commander 330");
    let role340 = message.guild.roles.find("name", "Commander 340");
    let role350 = message.guild.roles.find("name", "Commander 350");
    let role360 = message.guild.roles.find("name", "Commander 360");
    let role370 = message.guild.roles.find("name", "Commander 370");
    let role380 = message.guild.roles.find("name", "Commander 380");
    let role390 = message.guild.roles.find("name", "Commander 390");
    let role400 = message.guild.roles.find("name", "Commander 400");

    let server1 = message.guild.roles.find("name", "S1");
    let server2 = message.guild.roles.find("name", "S2");
    let server3 = message.guild.roles.find("name", "S3");
    let server4 = message.guild.roles.find("name", "S4");
    let server5 = message.guild.roles.find("name", "S5");
    let server6 = message.guild.roles.find("name", "S6");
    let server7 = message.guild.roles.find("name", "S7");

    const nearestDozen = (n) => {
        const str = n.toString()
        const withoutLast = str.slice(0, str.length - 1)
        return Number(withoutLast + 0)
    }

    const rank = {
        color: 0x33cc33,
        fields: [
            {
                name: message.author.tag,
                value: 'You are **__Commander ' + nearestDozen(args[1]) + '__**',
            },
        ],
        timestamp: new Date(),
        footer: {
            text: '@Bot MSI#9822',
            icon_url: message.author.avatarURL,
        },
    };

    const error = {
        color: 0x33cc33,
        title: message.author.tag,
        description: "You made a mistake in the command. Please try again. If the problem problem persists you can contact an Administrator, a Moderator or @Zurix#3717. \n Syntax of the commande: **__?rank cl xx__ or __?rank commander xx__** (xx is your commander level).",
        timestamp: new Date(),
        footer: {
            text: '@Bot MSI#9822',
            icon_url: message.author.avatarURL,
        },
    };

    let pseudoBef = message.member.displayName
    let pseudo2 = message.member.displayName.slice(0, pseudoBef.length - 9) + " [CL " + args[1] + "]"
    let pseudoDeb2 = pseudoBef.slice(pseudoBef.length - 8, pseudoBef.length - 7)
    let pseudoFin2 = pseudoBef.slice(pseudoBef.length - 1, pseudoBef.length - 0)

    let member = message.member
    let memberU = message.author.tag

    let memberM = message.mentions.members.first();
        if (memberM) {
            if (message.member.hasPermission('ADMINISTRATOR')) {
            member = memberM
            memberU = memberM.user.tag
            } else
            return message.channel.send("Permissions")
        }

        // if(args[1] && args[0] != "server" && args[0] != "s1" && args[0] != "s2" && args[0] != "s3" && args[0] != "s4" && args[0] != "s5" && args[0] != "s6" && args[0] != "s7"){
        //     member.removeRole(role10)
        //     member.removeRole(role20)
        //     member.removeRole(role30)
        //     member.removeRole(role40)
        //     member.removeRole(role50)
        //     member.removeRole(role60)
        //     member.removeRole(role70)
        //     member.removeRole(role80)
        //     member.removeRole(role90)
        //     member.removeRole(role100)
        //     member.removeRole(role110)
        //     member.removeRole(role120)
        //     member.removeRole(role130)
        //     member.removeRole(role140)
        //     member.removeRole(role150)
        // }

        if (args[0] == "commander" || args[0] == "cl") {
            if (nearestDozen(args[1]) == 10){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL  " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role150)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 20){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL  " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role20)
                member.removeRole(role10)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role150)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 30){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL  " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role30)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role150)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 40){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL  " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role40)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role150)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 50){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL  " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role50)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role150)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 60){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL  " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role60)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role150)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 70){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL  " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role70)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role150)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 80){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL  " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role80)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role150)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 90){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL  " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role90)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role150)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 100){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role100)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role150)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 110){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role110)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role150)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 120){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role120)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role150)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 130){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role130)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role140)
                member.removeRole(role150)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 140){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role140)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role150)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 150){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role150)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 160){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role150)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 170){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role150)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role160)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 180){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role150)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 190){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role150)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 200){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role150)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 210){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role150)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 220){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role150)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 230){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role150)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 240){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role150)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 250){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role150)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 260){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role150)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 270){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role150)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 280){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role150)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 290){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role150)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 300){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role150)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 310){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role150)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 320){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role150)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 330){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role150)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 340){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role150)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 350){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role150)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 360){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role150)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 370){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role150)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role380)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 380){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role150)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role390)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 390){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role150)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role400)
            }else if(nearestDozen(args[1]) == 400){
                if(pseudoDeb2 == "[" && pseudoFin2 == "]"){member.setNickname(pseudo2)}else member.setNickname(pseudoBef + " [CL " + args[1] + "]")
                message.channel.send({ embed: rank });
                member.addRole(role150)
                member.removeRole(role10)
                member.removeRole(role20)
                member.removeRole(role30)
                member.removeRole(role40)
                member.removeRole(role50)
                member.removeRole(role60)
                member.removeRole(role70)
                member.removeRole(role80)
                member.removeRole(role90)
                member.removeRole(role100)
                member.removeRole(role110)
                member.removeRole(role120)
                member.removeRole(role130)
                member.removeRole(role140)
                member.removeRole(role160)
                member.removeRole(role170)
                member.removeRole(role180)
                member.removeRole(role190)
                member.removeRole(role200)
                member.removeRole(role210)
                member.removeRole(role220)
                member.removeRole(role230)
                member.removeRole(role240)
                member.removeRole(role250)
                member.removeRole(role260)
                member.removeRole(role270)
                member.removeRole(role280)
                member.removeRole(role290)
                member.removeRole(role300)
                member.removeRole(role310)
                member.removeRole(role320)
                member.removeRole(role330)
                member.removeRole(role340)
                member.removeRole(role350)
                member.removeRole(role360)
                member.removeRole(role370)
                member.removeRole(role380)
                member.removeRole(role390)
            }else{
                message.channel.send({embed: error });
            }
        }


        if(args[0] == "server"){
            switch(args[1]) {
                case "1":
                member.addRole(server1)
                message.channel.send({embed: {
                                        color: 0x33cc33,
                                        description: "You are **S1**!"
                                    }});
                break;
    
                case "2":
                member.addRole(server2)
                message.channel.send({embed: {
                                        color: 0x33cc33,
                                        description: "You are **S2** !"
                                    }});
                break;
    
                case "3":
                member.addRole(server3)
                message.channel.send({embed: {
                                        color: 0x33cc33,
                                        description: "You are **S3** !"
                                    }});
                break;
    
                case "4":
                member.addRole(server4)
                message.channel.send({embed: {
                                        color: 0x33cc33,
                                        description: "You are **S4** !"
                                    }});
                break;
    
                case "5":
                member.addRole(server5)
                message.channel.send({embed: {
                                        color: 0x33cc33,
                                        description: "You are **S5** !"
                                    }});
                break;
                case "6":
                member.addRole(server6)
                message.channel.send({embed: {
                                        color: 0x33cc33,
                                        description: "You are **S6** !"
                                    }});
                break;  
                case "7":
                member.addRole(server7)
                message.channel.send({embed: {
                                        color: 0x33cc33,
                                        description: "You are **S7** !"
                                    }});
                break;             
                default:
                    return message.channel.send({embed: {
                            color: 0x33cc33,
                            description: "You made a mistake in the command. Do ?rank server xx (xx is your server)."
                            }})
            }          
        }else if(args[0] == "s1"){
            member.addRole(server1)
            message.channel.send({embed: {
                                    color: 0x33cc33,
                                    description: "You are **S1** !"
                                }});
        }else if(args[0] == "s2"){
            member.addRole(server2)
            message.channel.send({embed: {
                                    color: 0x33cc33,
                                    description: "You are **S2** !"
                                }});
        }else if(args[0] == "s3"){
            member.addRole(server3)
            message.channel.send({embed: {
                                    color: 0x33cc33,
                                    description: "You are **S3** !"
                                }});
        }else if(args[0] == "s4"){
            member.addRole(server4)
            message.channel.send({embed: {
                                    color: 0x33cc33,
                                    description: "You are **S4** !"
                                }});
        }else if(args[0] == "s5"){
            member.addRole(server5)
            message.channel.send({embed: {
                                    color: 0x33cc33,
                                    description: "You are **S5** !"
                                }});    
        }else if(args[0] == "s6"){
            member.addRole(server6)
            message.channel.send({embed: {
                                    color: 0x33cc33,
                                    description: "You are **S6** !"
                                }});   
        }else if(args[0] == "s7"){
            member.addRole(server7)
            message.channel.send({embed: {
                                    color: 0x33cc33,
                                    description: "You are **S7** !"
                                }});   
        }
}